{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.frozenmilk.sinister",
    "module": "Sloth",
    "version": "SNAPSHOT-fea55d8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.frozenmilk",
          "module": "Sinister",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "Sloth-SNAPSHOT-fea55d8.aar",
          "url": "Sloth-SNAPSHOT-fea55d8.aar",
          "size": 172325,
          "sha512": "e95b689efb02faacfbf2a751b6e8292626380206efe523c6be512308d3fec39b0b1058d691bc2a0fcfc052db0a6dce00efad84a05bc57e8f98102799f048619e",
          "sha256": "ec5760554c2d76ec5faf0a0954a54494b6887740c70bf1c34f5618c99fffb8fd",
          "sha1": "f6890b68b18e0367d20e4692562b0879f1b06ea3",
          "md5": "7ac81bf3de35ee71dbbd563301e1ee0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.frozenmilk",
          "module": "Sinister",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "Sloth-SNAPSHOT-fea55d8.aar",
          "url": "Sloth-SNAPSHOT-fea55d8.aar",
          "size": 172325,
          "sha512": "e95b689efb02faacfbf2a751b6e8292626380206efe523c6be512308d3fec39b0b1058d691bc2a0fcfc052db0a6dce00efad84a05bc57e8f98102799f048619e",
          "sha256": "ec5760554c2d76ec5faf0a0954a54494b6887740c70bf1c34f5618c99fffb8fd",
          "sha1": "f6890b68b18e0367d20e4692562b0879f1b06ea3",
          "md5": "7ac81bf3de35ee71dbbd563301e1ee0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Sloth-SNAPSHOT-fea55d8-sources.jar",
          "url": "Sloth-SNAPSHOT-fea55d8-sources.jar",
          "size": 39793,
          "sha512": "65da2d4ca5d6f56efbcc7798dd3175bed0722d0a5c9b9dbe04ea65621b15131e887a4fd962e6aaf75d33e248638f967ed37f859e45e053b8ecc26269b69765a8",
          "sha256": "470a036989575d866ad41c50e80dce80e84e84908a62dc6fd2ba0cb6b6e43a7e",
          "sha1": "5d4c6af0beffb96ebb1acf7e97c89a3fb0908974",
          "md5": "a2cdbe1fe7cd426f5596118e5b0a516a"
        }
      ]
    }
  ]
}
