{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.frozenmilk.sinister",
    "module": "Sloth",
    "version": "SNAPSHOT-8ec1274",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.frozenmilk",
          "module": "Sinister",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "Sloth-SNAPSHOT-8ec1274.aar",
          "url": "Sloth-SNAPSHOT-8ec1274.aar",
          "size": 172325,
          "sha512": "e1bd93e484736d569fb866c73f60da0e9cb394c3a4a16d78994677f182e66faeb517d343767744d0ebdd64641dbc79662b473b70ee809a4f16236ada34428c92",
          "sha256": "0a5a173ccf445f63d1112b96861310825701e422fb3b9694b3a541bcd180a1aa",
          "sha1": "73c9b07e7bcd720ff01081b085d37f43ddd271ec",
          "md5": "1470cc3eca8193651357abe179cb2a5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.frozenmilk",
          "module": "Sinister",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "Sloth-SNAPSHOT-8ec1274.aar",
          "url": "Sloth-SNAPSHOT-8ec1274.aar",
          "size": 172325,
          "sha512": "e1bd93e484736d569fb866c73f60da0e9cb394c3a4a16d78994677f182e66faeb517d343767744d0ebdd64641dbc79662b473b70ee809a4f16236ada34428c92",
          "sha256": "0a5a173ccf445f63d1112b96861310825701e422fb3b9694b3a541bcd180a1aa",
          "sha1": "73c9b07e7bcd720ff01081b085d37f43ddd271ec",
          "md5": "1470cc3eca8193651357abe179cb2a5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Sloth-SNAPSHOT-8ec1274-sources.jar",
          "url": "Sloth-SNAPSHOT-8ec1274-sources.jar",
          "size": 39793,
          "sha512": "65da2d4ca5d6f56efbcc7798dd3175bed0722d0a5c9b9dbe04ea65621b15131e887a4fd962e6aaf75d33e248638f967ed37f859e45e053b8ecc26269b69765a8",
          "sha256": "470a036989575d866ad41c50e80dce80e84e84908a62dc6fd2ba0cb6b6e43a7e",
          "sha1": "5d4c6af0beffb96ebb1acf7e97c89a3fb0908974",
          "md5": "a2cdbe1fe7cd426f5596118e5b0a516a"
        }
      ]
    }
  ]
}
